### ISSUE TITLE
Tracker 1 evalucation

### ISSUE THREAD

**Issue by doyu** [ninjalabo/hsicomp#7]
TODO:

- [ ] Describe the model in a few sentences.
- [ ] Print (or visualize, explain, ...) ML model architecture
- [ ] Run the model
