### ISSUE TITLE
Tracker 2 evalucation

### ISSUE THREAD

**Issue by doyu** [ninjalabo/hsicomp#8]
ViPT

TODO:

- [ ] Describe the model in a few sentences.
- [ ] Print (or visualize, explain, ...) ML model architecture
- [ ] Run the model

**Comment by doyu** [comment]
Update here!

**Comment by leilaMozaffari8** [comment]
This is the error for training part.
![image](https://github.com/user-attachments/assets/4202ed7f-94c5-445c-8206-189975edfc01)

**Comment by leilaMozaffari8** [comment]
Now I don't have enough space. @doyu Can you increase the size of Scaleway?

![image](https://github.com/user-attachments/assets/de7f607a-e063-44a6-b11d-98d395b30779)

 sudo apt-get install --reinstall libnccl2 libnccl-dev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages were automatically installed and are no longer required:
  adwaita-icon-theme alsa-topology-conf alsa-ucm-conf at-spi2-core ca-certificates-java dconf-gsettings-backend
  dconf-service fontconfig fonts-dejavu-extra gsettings-desktop-schemas gtk-update-icon-cache hicolor-icon-theme
  humanity-icon-theme java-common libaccinj64-11.5 libasound2 libasound2-data libasyncns0 libatk-bridge2.0-0
  libatk-wrapper-java libatk-wrapper-java-jni libatk1.0-0 libatk1.0-data libatspi2.0-0 libavahi-client3
  libavahi-common-data libavahi-common3 libbabeltrace1 libboost-regex1.74.0 libcairo-gobject2 libcairo2
  libcub-dev libcublas11 libcublaslt11 libcudart11.0 libcufft10 libcufftw10 libcuinj64-11.5 libcups2
  libcupti-dev libcupti-doc libcupti11.5 libcurand10 libcusolver11 libcusolvermg11 libcusparse11 libdatrie1
  libdconf1 libdebuginfod-common libdebuginfod1 libdouble-conversion3 libegl-dev libegl-mesa0 libegl1 libflac8
  libfontenc1 libgail-common libgail18 libgbm1 libgdk-pixbuf-2.0-0 libgdk-pixbuf2.0-bin libgdk-pixbuf2.0-common
  libgif7 libgl-dev libgl1-mesa-dev libgles-dev libgles1 libgles2 libglvnd-core-dev libglvnd-dev libglx-dev
  libgraphite2-3 libgtk2.0-0 libgtk2.0-bin libgtk2.0-common libharfbuzz0b libice6 libipt2 liblcms2-2 libnppc11
  libnppial11 libnppicc11 libnppidei11 libnppif11 libnppig11 libnppim11 libnppist11 libnppisu11 libnppitc11
  libnpps11 libnvblas11 libnvidia-ml-dev libnvjpeg11 libnvrtc-builtins11.5 libnvrtc11.2 libnvtoolsext1 libnvvm4
  libogg0 libopengl-dev libopengl0 libopus0 libpango-1.0-0 libpangocairo-1.0-0 libpangoft2-1.0-0 libpcre2-16-0
  libpcsclite1 libpixman-1-0 libpthread-stubs0-dev libpulse0 libqt5core5a libqt5dbus5 libqt5network5 librsvg2-2
  librsvg2-common libsm6 libsndfile1 libsource-highlight-common libsource-highlight4v5 libtbb-dev libtbb12
  libtbbmalloc2 libthai-data libthai0 libthrust-dev libvdpau-dev libvdpau1 libvorbis0a libvorbisenc2
  libwayland-client0 libwayland-cursor0 libwayland-egl1 libwayland-server0 libx11-dev libxau-dev libxaw7
  libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-render-util0 libxcb-render0 libxcb-shape0 libxcb-util1
  libxcb-xinerama0 libxcb-xkb1 libxcb1-dev libxcomposite1 libxcursor1 libxdamage1 libxdmcp-dev libxft2 libxi6
  libxinerama1 libxkbcommon-x11-0 libxkbcommon0 libxkbfile1 libxmu6 libxrandr2 libxrender1 libxt6 libxtst6
  libxv1 libxxf86dga1 mesa-vdpau-drivers node-html5shiv nvidia-cuda-gdb nvidia-cuda-toolkit-doc
  nvidia-firmware-550-550.107.02 nvidia-opencl-dev nvidia-profiler ocl-icd-libopencl1 ocl-icd-opencl-dev
  opencl-c-headers opencl-clhpp-headers openjdk-8-jre openjdk-8-jre-headless qttranslations5-l10n
  session-migration ubuntu-mono vdpau-driver-all x11-common x11-utils x11proto-dev xorg-sgml-doctools xtrans-dev
Use 'sudo apt autoremove' to remove them.
The following NEW packages will be installed:
  libnccl-dev libnccl2
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
183 not fully installed or removed.
Need to get 238 MB of archives.
After this operation, 516 MB of additional disk space will be used.
E: You don't have enough free space in /var/cache/apt/archives/.

**Comment by doyu** [comment]
Now it's 180GB. If you need more, I'll! Please talk with @harukadoyu & @dheeraj1856 how to evaluate further together

![image](https://github.com/user-attachments/assets/8c3dff82-8029-42f9-9edf-0f863aa73d43)
