### ISSUE TITLE
Tracker 3 evalucation

### ISSUE THREAD

**Issue by doyu** [ninjalabo/hsicomp#9]
TODO:

- [ ] Describe the model in a few sentences.
- [ ] Print (or visualize, explain, ...) ML model architecture
- [ ] Run the model

**Comment by doyu** [comment]
Update here!
